### ISSUE TITLE
Views extracting YAML fields with line continuation characters fail

### ISSUE THREAD

**Issue by jackwhelpton** [jdkato/txtlint#1018]
### Check for existing issues

- [x] Completed

### Environment

OS: Linux
Install method: direct download
Vale version: 3.12.0

### Describe the bug / provide steps to reproduce it

YAML file such as:

```yaml
openapi: 3.0.1
info:
  description: "Line 1\
    \ Line 2"
```

view:

```yaml
engine: dasel
scopes:
  # API info
  - expr: info.description
    name: title
```

Error:

```
E100 [test.yaml] Runtime error

'Line 1 Line 2' not found

Execution stopped with code 1.
```

Verified this extracts the correct string from the Dasel Playground.
