### ISSUE TITLE
Difficulties in using regex filters in spelling.yml

### ISSUE THREAD

**Issue by adam-balogh** [jdkato/txtlint#363]
Hi,

I use Vale for quite a long time now, and it works really great.
I want to update one of our style guide by adding filters to the spelling yml. After the change, I'm still getting errors referring to the lines I try to ignore.

The content of the `spelling.yml` file:

```yml
extends: spelling
message: "'%s' is a typo!"
custom: true
level: error
filters:
- '`[a-zA-Z0-9_\/\.\-"\{\} :@<>%$_,\.;\(\)]+`' # to ignore inline codes
- '\x60\x60\x60[0-9A-Za-z]+\n[ 0-9A-Za-z!\x60"#$%&\(\)\*\+,\-.\/:;<=>?@\[\\\]^_{|}~\]\n]+?\x60\x60\x60' # to ignore fenced code blocks
- '\[[ 0-9A-Za-z!"#$%&\(\)\*\+,\-.\/:;<=>?@\[\\\]^_\x60{|}~\]]+\]\([ 0-9A-Za-z!"#$%&\(\)\*\+,\-.\/:;<=>?@\[\\\]^_\x60{|}~\]]+\)' # to ignore md links
- 'uid[0-9]*'
- '[0-9]+[\.0-9]*px'
- 'group[0-9]*'
- 'alpha[\.0-9]*'
- 'q[1-4]+'
- 'tab[0-9]*'
- 'header[0-9]*'
- 'h[0-9]*'
- 'heading[0-9]*'
ignore:
  - Internal/ignore/base.txt
```

**Example:**

_Source file (MD):_

```md
Add the following:

    ```md
    Host code.company-name.net
    User your-gerrit-username1
    Port 123456
    ```

    ```bash
    for i in $PWD/git-hooks/*; do ln -s $i .git/hooks/; done
    ```
```
_Output:_

`error       'username1' is a typo!             Internal.Spelling`
`error       'PWD' is a typo!                       Internal.Spelling`

_Expected behaviour:_

Don't list the errors in lines that match with the given regex patterns.

The regex patterns work as expected outside Vale. I tested them with [Rego](https://regoio.herokuapp.com/) and [regex101](https://regex101.com/). Please help me find out what could cause the problem. Thank you for your help in advance.

- OS: macOS Catalina 10.15
- Install method: Homebrew
- Vale version: 1.7.1
- Usage method: from CLI, `vale --ignore-syntax`
