### ISSUE TITLE
Can't add words with spaces to exceptions

### ISSUE THREAD

**Issue by Stanzilla** [jdkato/txtlint#401]
- OS (e.g., macOS, Windows, Linux, etc.) - Linux
- Install method (e.g., Go, Homebrew, direct download, etc.) - Homebrew
- Vale version (the result of `vale -v`) - 2.14

I'm trying to add an exception to https://developers.google.com/style/pronouns#personal-pronouns for these two:

```
**My Templates**
**My Scripts**
```

but it does not seem to work, also it won't let me use * in general because that has search implications, but it's also commonly used in Markdown. Any suggestions?

**Comment by jdkato** [comment]
Could you provide an example of how and where you're adding this exception? 

In general, you *can* use spaces and `*` can be escaped.

**Comment by Stanzilla** [comment]
> Could you provide an example of how and where you're adding this exception?
> 
> In general, you _can_ use spaces and `*` can be escaped.

```yml
exceptions:
  - My Templates
```

in FirstPerson.yml

The text appears like this in markdown:

```md
2. Click on **My Templates**
```

**Comment by jdkato** [comment]
`FirstPerson.yml` only looks for instances of "my" (single-word), so an exception like "My Templates" will never match.

You can create a custom rule that works as you'd like, though:

```yaml
extends: existence
message: "Avoid first-person pronouns such as '%s'."
ignorecase: true
level: warning
tokens:
  - 'my \w+'
exceptions:
  - My Templates
  - My Scripts
```
