### ISSUE TITLE
YAML -> Markdown: scopes mapping

### ISSUE THREAD

**Issue by plaindocs** [jdkato/txtlint#412]
Hey @jdkato 

As usual, thanks for Vale. 

Would you be able to give me a couple of pointers to where I would start looking at mapping a custom YAML format to vale markdown scopes?

Something like given a YAML of 

```
items:
  - id: 1234
    name: real name
    description: this is some tex
...
```

I'd need to say ignore `id`, ignore `name`, and lint `description` as paragraph. Does that sound doable?
