### ISSUE TITLE
Multi-document rule support

### ISSUE THREAD

**Issue by brsolomon-deloitte** [jdkato/txtlint#429]
Vale appears to not support multi-document YAML inputs:

```yaml
extends: substitution
message: There may not be an objecti...
level: error
ignorecase: true
swap:
  '(?:perfect|perfected|perfection)': required|necessary|needed|reasonable|agreed|specified|adequate|compliant

---

extends: substitution
message: The use of this word could imply ...
level: error
ignorecase: true
swap:
  '(?:experts?|expertise)': skilled|practiced|knowledgeable|proficient|practitioner|consultant|experienced
```

From this rule, it only picks up the first yaml document.

Most YAML parsers support reading multi-doc inputs. Could vale leverage this too?
