### ISSUE TITLE
Sequence rule captures pattern inside composite words, too

### ISSUE THREAD

**Issue by theletterf** [jdkato/txtlint#505]
When using `extends: sequence`, I'm seemingly unable to define certain regex patterns. This results in patterns being detected also inside longer composite words.

For example:

```yaml
extends: sequence
message: "Use data and metadata as mass nouns (singular)."
link: 'https://docs.splunk.com/Documentation/StyleGuide/current/StyleGuide/Usagedictionary#D'
level: suggestion
ignorecase: true
tokens:
  - pattern: '(?:data|metadata)'
  - tag: VBP
```

Results in `data are` matching, but also `databases are`, which shouldn't. I've tried using `nonword: false` (which I guess isn't supported by `sequence` anyway) and `\s`, which work for other extensions, to no avail.

How can I tell Vale to just grab `data\s`?

**Comment by theletterf** [comment]
This works (thanks, @CollierCZ!):

```
extends: sequence
level: suggestion
ignorecase: true
tokens:
  - pattern: '\b(?:data|metadata)\b'
  - tag: VBP
``` 

Perhaps we need to document this workaround?
