### ISSUE TITLE
Spelling with hunspell-nl dictionary results in error E201 Invalid value

### ISSUE THREAD

**Issue by koenvervloesem** [jdkato/txtlint#776]
### Check for existing issues

- [X] Completed

### Environment

* Ubuntu 22.04.3 LTS
* Vale installed from PyPI with `pip3 install -U vale`
* Vale 3.1.0

### Describe the bug / provide steps to reproduce it

I wrote the following rule to add Dutch spelling:

```yaml
extends: spelling
message: "Bedoelde je echt '%s'?"
level: error
dicpath: /usr/share/hunspell/
dictionaries:
  - nl
```

I installed the hunspell-nl package (`sudo apt install hunspell-nl`), which is created by the [OpenTaal](https://github.com/OpenTaal/opentaal-hunspell) project.

After running Vale on a Dutch text with this rule enabled, I get the following error:

```
E201 Invalid value [/home/koan/vale/Koen_NL/spelling.yml:1:1]:

   1* extends: spelling
   2  message: "Bedoelde je echt '%s'?"
   3  level: error

CrossProduct is not Y or N: got "0"

Execution stopped with code 1.
```

When I change the dictionary to `en` in the spelling rule, running Vale succeeds, so there's something in the Dutch dictionary file that makes it fail.
