### ISSUE TITLE
Vale does not detect errors

### ISSUE THREAD

**Issue by ariebonn** [jdkato/txtlint#999]
### Check for existing issues

- [x] Completed

### Environment

OS: Ubuntu 22.04.5 LTS
Install method: sudo snap install vale
Vale version:  v3.11.2

### Describe the bug / provide steps to reproduce it

I installed Vale and am having trouble getting it to work. First issue is that it only works with a .vale.ini file from `/home/arie/.config/vale`. If I place the Vale file in my repo root it doesn't find it, even if I specify the `--config` option. It's weird because the file is there, but it says that it doesn't exist.

Anyways, I figured that it works when the Vale file is in the home folder so I tried to test it with an MD file. This is my config:

```
StylesPath = styles
MinAlertLevel = suggestion
Packages = RedHat, proselint
[*]
BasedOnStyles = Vale, RedHat, proselint, Test
```
I executed `vale sync` and verified it downloaded the styles.

I created a custom style in the Test folder:

```
extends: substitution
message: Consider using '%s' instead of '%s'
link: 'www.internal-tools.io'
level: warning
ignorecase: false
action:
 name: replace
# swap maps tokens in the form of bad: good
swap:
   applications: apps
   config: configuration
```

And created the following MD file:

```
# Hello World!?!

Hello world world. You can use your internal tools too build your own production grade applications config.
```

When I execute Vale on the file it outputs:

```
✔ 0 errors, 0 warnings and 0 suggestions in stdin.
```
Would appreciate any help in determining what I'm doing wrong.
